# Generated by Django 4.0.3 on 2022-03-28 18:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(blank=True, max_length=200, verbose_name='Recipe name')),
                ('recipe_ingredients', models.TextField(default='', help_text='Enter as a list separated by commas')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='published')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.TextField(default='', verbose_name='Ingredients')),
                ('utensils', models.TextField(default='', verbose_name='Utensils')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
