# Generated by Django 4.0.3 on 2022-04-07 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recipes',
            field=models.JSONField(default=list, verbose_name='Recipes'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Created'),
        ),
    ]
