# Generated by Django 4.0.3 on 2022-03-28 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mainApp', '0002_newuser_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ingredients', models.TextField(default='', verbose_name='Ingredients')),
                ('utensils', models.TextField(default='', verbose_name='Utensils')),
            ],
        ),
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
