# Generated by Django 4.0.3 on 2022-04-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_profile_recipe_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='recipe_ids',
            field=models.TextField(blank=True, default='', verbose_name='Recipes'),
        ),
    ]
