# Generated by Django 4.0.3 on 2022-03-07 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='title',
        ),
        migrations.AddField(
            model_name='recipe',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='published'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='', help_text='Enter as a list separated by commas'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(default=100, max_length=200, verbose_name='Recipe name'),
            preserve_default=False,
        ),
    ]
