# Generated by Django 4.0.3 on 2022-04-07 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_profile_recipes_alter_recipe_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainApp.profile'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='comments',
            field=models.JSONField(default=list, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.JSONField(default=tuple, verbose_name='Instructions'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ratings',
            field=models.JSONField(default=list, verbose_name='Ratings'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_utensils',
            field=models.JSONField(default=list, verbose_name='Utensils'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_ingredients',
            field=models.JSONField(default=list, verbose_name='Ingredients'),
        ),
    ]
