# Generated by Django 4.0.3 on 2022-04-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_profile_recipe_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='comments',
            field=models.JSONField(default=list, verbose_name='Comments'),
        ),
    ]
