# Generated by Django 4.0.3 on 2022-03-22 17:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_remove_recipe_pub_date_remove_recipe_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Recipe Name'),
        ),
    ]
