# Generated by Django 4.0.3 on 2022-03-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_profile_delete_newuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ingredients_list',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Ingredient list'),
        ),
    ]
