# Generated by Django 4.0.3 on 2022-03-24 20:20

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_remove_recipe_ingredients_remove_recipe_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='', help_text='Enter as a list separated by commas'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Recipe name'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
