# Generated by Django 4.0.3 on 2022-03-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_recipe_ingredients_recipe_recipe_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients',
            new_name='recipe_ingredients',
        ),
    ]
